'use strict';function t(f,a,b,d){f.v.kc(f.Ya,a,b,d,void 0)}function E(f,a,b,d){f.v.ra?t(f,a,b,d):f.v.ef()._OnMessageFromDOM({type:"event",component:f.Ya,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function G(f,a,b){f.v.C(f.Ya,a,b)}function I(f,a){for(const [b,d]of a)G(f,b,d)}function J(f){f.Ob||(f.v.Qe(f.$d),f.Ob=!0)}window.Qa=class{constructor(f,a){this.v=f;this.Ya=a;this.Ob=!1;this.$d=()=>this.Da()}cd(){}Da(){}};function K(f){-1!==f.Oa&&(self.clearTimeout(f.Oa),f.Oa=-1)}
window.He=class{constructor(f,a){this.Kc=f;this.rg=a;this.Oa=-1;this.Pb=-Infinity;this.ae=()=>{this.Oa=-1;this.Pb=Date.now();this.cb=!0;this.Kc();this.cb=!1};this.Jd=this.cb=!1}c(){K(this);this.ae=this.Kc=null}};"use strict";function L(f,a){G(f,"get-element",b=>{const d=f.ca.get(b.elementId);return a(d,b)})}
window.Kg=class extends self.Qa{constructor(f,a){super(f,a);this.ca=new Map;this.Jc=!0;I(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const d=this.ca.get(b);this.Jc&&d.parentElement.removeChild(d);this.ca.delete(b)}}],["set-visible",b=>{this.Jc&&(this.ca.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Jc){var d=this.ca.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=
b.height+"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.ca.get(b.elementId);throw Error("required override");}],["focus",b=>this.Ec(b)],["set-css-style",b=>{this.ca.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ca.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ca.get(b.elementId).removeAttribute(b.name)}]]);L(this,b=>b)}Ec(f){var a=this.ca.get(f.elementId);f.focus?a.focus():a.blur()}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(k,c){const h=document.createElement("script");h.async=!1;"module"===c&&(h.type="module");return k.Bg?new Promise(l=>{const n="c3_resolve_"+a;++a;self[n]=l;h.textContent=k.Eg+`\n\nself["${n}"]();`;document.head.appendChild(h)}):new Promise((l,n)=>{h.onload=l;h.onerror=n;h.src=k;document.head.appendChild(h)})}let d=!1,g=!1;function m(){if(!d){try{new Worker("blob://",{get type(){g=!0}})}catch(k){}d=
!0}return g}let p=new Audio;const w={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function A(k){k=await B(k);return(new TextDecoder("utf-8")).decode(k)}function B(k){return new Promise((c,
h)=>{const l=new FileReader;l.onload=n=>c(n.target.result);l.onerror=n=>h(n);l.readAsArrayBuffer(k)})}const v=[];let x=0;window.RealFile=window.File;const C=[],y=new Map,D=new Map;let F=0;const H=[];self.runOnStartup=function(k){if("function"!==typeof k)throw Error("runOnStartup called without a function");H.push(k)};const e=new Set(["cordova","playable-ad","instant-games"]);window.Ua=class k{constructor(c){this.ra=c.Gg;this.pa=null;this.F="";this.Xb=c.Dg;this.da=c.de;this.rb={};this.Ha=this.qb=null;
this.Mb=[];this.fb=this.K=this.Ma=null;this.La=-1;this.wg=()=>this.Df();this.Ka=[];this.B=c.be;!this.ra||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&("module"!==this.da||m())||(this.ra=!1);e.has(this.B)&&this.ra&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this.ra=!1);this.Rb=this.ia=null;"html5"!==this.B&&"playable-ad"!==this.B||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
this.C("runtime","cordova-fetch-local-file",h=>this.mf(h));this.C("runtime","create-job-worker",()=>this.nf());"cordova"===this.B?document.addEventListener("deviceready",()=>this.vd(c)):this.vd(c)}c(){this.qc();this.pa&&(this.pa=this.pa.onmessage=null);this.qb&&(this.qb.terminate(),this.qb=null);this.Ha&&(this.Ha.c(),this.Ha=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}ld(){return f&&"cordova"===this.B}jc(){return f&&e.has(this.B)||navigator.standalone}async vd(c){if("playable-ad"===
this.B){this.ia=self.c3_base64files;this.Rb={};await this.Ve();for(let l=0,n=c.Pa.length;l<n;++l){var h=c.Pa[l].toLowerCase();this.Rb.hasOwnProperty(h)?c.Pa[l]={Bg:!0,Eg:this.Rb[h]}:this.ia.hasOwnProperty(h)&&(c.Pa[l]=URL.createObjectURL(this.ia[h]))}}c.xg?this.F=c.xg:(h=location.origin,this.F=("null"===h?"file:///":h)+location.pathname,h=this.F.lastIndexOf("/"),-1!==h&&(this.F=this.F.substr(0,h+1)));c.Ig&&(this.rb=c.Ig);h=new MessageChannel;this.pa=h.port1;this.pa.onmessage=l=>this._OnMessageFromRuntime(l.data);
window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.zf(l));this.fb=new self.De(this);await M(this.fb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ra?await this.gf(c,h.port2):await this.ff(c,h.port2)}tc(c){c=this.rb.hasOwnProperty(c)?this.rb[c]:c.endsWith("/workermain.js")&&this.rb.hasOwnProperty("workermain.js")?this.rb["workermain.js"]:"playable-ad"===this.B&&this.ia.hasOwnProperty(c.toLowerCase())?
this.ia[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async bc(c,h,l){if(c.startsWith("blob:"))return new Worker(c,l);if(this.ld()&&"file:"===location.protocol)return c=await this.ub(this.Xb+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,h);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,
l)}wa(){return Math.max(window.innerWidth,1)}va(){return Math.max(window.innerHeight,1)}ud(c){var h=this.fb;return{baseUrl:this.F,windowInnerWidth:this.wa(),windowInnerHeight:this.va(),devicePixelRatio:window.devicePixelRatio,isFullscreen:k.ic(),projectData:c.Pg,scriptsType:c.de,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Ng||"",exportType:c.be,isDebug:-1<self.location.search.indexOf("debug"),
ife:!!self.Og,jobScheduler:{inputPort:h.Qc,outputPort:h.Xc,maxNumWorkers:h.tg},supportedAudioFormats:w,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Xb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Xb+"opus.wasm.wasm",isiOSCordova:this.ld(),isiOSWebView:this.jc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async gf(c,h){var l=this.tc(c.Hg);this.qb=await this.bc(l,this.F,{type:this.da,name:"Runtime"});this.K=document.createElement("canvas");this.K.style.display=
"none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;this.qb.postMessage(Object.assign(this.ud(c),{type:"init-runtime",isInWorker:!0,messagePort:h,canvas:l,workerDependencyScripts:c.bd||[],engineScripts:c.Pa,projectScripts:c.sb,mainProjectScript:c.ce,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[h,l,...N(this.fb)]);this.Mb=C.map(n=>new n(this));this.td();self.c3_callFunction=(n,q)=>this.Ma.hf(n,q);"preview"===this.B&&(self.goToLastErrorScript=
()=>this.kc("runtime","go-to-last-error-script"))}async ff(c,h){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Mb=C.map(q=>new q(this));this.td();var l=c.Pa.map(q=>"string"===typeof q?(new URL(q,this.F)).toString():q);Array.isArray(c.bd)&&l.unshift(...c.bd);l=await Promise.all(l.map(q=>this.xc(q,this.da)));await Promise.all(l.map(q=>b(q,this.da)));const n=self.C3_ProjectScriptsStatus;if("module"===this.da){l=c.ce;const q=
c.sb;for(let [u,r]of q)if(r||(r=u),u===l)try{r=await this.xc(r,this.da),await b(r,this.da),"preview"!==this.B||n[u]||this.Dd(u,"main script did not run to completion")}catch(z){this.Dd(u,z)}else if("scriptsInEvents.js"===u||u.endsWith("/scriptsInEvents.js"))r=await this.xc(r,this.da),await b(r,this.da)}else if(c.sb&&0<c.sb.length)try{if(await Promise.all(c.sb.map(q=>b(q[1],this.da))),Object.values(n).some(q=>!q)){self.setTimeout(()=>this.Ed(n),100);return}}catch(q){console.error("[Preview] Error loading project scripts: ",
q);self.setTimeout(()=>this.Ed(n),100);return}"preview"===this.B&&"object"!==typeof self.Jg.Lg?(this.Wa(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.ud(c),{isInWorker:!1,messagePort:h,canvas:this.K,runOnStartupFunctions:H}),this.xd(),this.Ha=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ha,
c))}Ed(c){this.Wa();c=`Failed to load project script '${Object.entries(c).filter(h=>!h[1]).map(h=>h[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+c);alert(c)}Dd(c,h){this.Wa();console.error(`[Preview] Failed to load project main script (${c}): `,h);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}xd(){this.Wa()}Wa(){const c=window.yg;c&&(c.parentElement.removeChild(c),
window.yg=null)}async nf(){const c=await O(this.fb);return{outputPort:c,transferables:[c]}}ef(){if(this.ra)throw Error("not available in worker mode");return this.Ha}kc(c,h,l,n,q){this.pa.postMessage({type:"event",component:c,handler:h,dispatchOpts:n||null,data:l,responseId:null},q)}md(c,h,l,n,q){const u=F++,r=new Promise((z,R)=>{D.set(u,{resolve:z,reject:R})});this.pa.postMessage({type:"event",component:c,handler:h,dispatchOpts:n||null,data:l,responseId:u},q);return r}["_OnMessageFromRuntime"](c){const h=
c.type;if("event"===h)return this.tf(c);if("result"===h)this.Gf(c);else if("runtime-ready"===h)this.Hf();else if("alert-error"===h)this.Wa(),alert(c.message);else if("creating-runtime"===h)this.xd();else throw Error(`unknown message '${h}'`);}tf(c){const h=c.component,l=c.handler,n=c.data,q=c.responseId;if(c=y.get(h))if(c=c.get(l)){var u=null;try{u=c(n)}catch(r){console.error(`Exception in '${h}' handler '${l}':`,r);null!==q&&this.Fb(q,!1,""+r);return}if(null===q)return u;u&&u.then?u.then(r=>this.Fb(q,
!0,r)).catch(r=>{console.error(`Rejection from '${h}' handler '${l}':`,r);this.Fb(q,!1,""+r)}):this.Fb(q,!0,u)}else console.warn(`[DOM] No handler '${l}' for component '${h}'`);else console.warn(`[DOM] No event handlers for component '${h}'`)}Fb(c,h,l){let n;l&&l.transferables&&(n=l.transferables);this.pa.postMessage({type:"result",responseId:c,isOk:h,result:l},n)}Gf(c){const h=c.responseId,l=c.isOk;c=c.result;const n=D.get(h);l?n.resolve(c):n.reject(c);D.delete(h)}C(c,h,l){let n=y.get(c);n||(n=new Map,
y.set(c,n));if(n.has(h))throw Error(`[DOM] Component '${c}' already has handler '${h}'`);n.set(h,l)}static tb(c){if(C.includes(c))throw Error("DOM handler already added");C.push(c)}td(){for(const c of this.Mb)if("runtime"===c.Ya){this.Ma=c;return}throw Error("cannot find runtime DOM handler");}zf(c){this.kc("debugger","message",c)}Hf(){for(const c of this.Mb)c.cd()}static ic(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Qe(c){this.Ka.push(c);
this.Hc()}Sf(c){c=this.Ka.indexOf(c);if(-1===c)throw Error("invalid callback");this.Ka.splice(c,1);this.Ka.length||this.qc()}Hc(){-1===this.La&&this.Ka.length&&(this.La=requestAnimationFrame(this.wg))}qc(){-1!==this.La&&(cancelAnimationFrame(this.La),this.La=-1)}Df(){this.La=-1;for(const c of this.Ka)c();this.Hc()}ua(c){this.Ma.ua(c)}Ca(c){this.Ma.Ca(c)}Gc(){this.Ma.Gc()}Ab(c){this.Ma.Ab(c)}Ce(){return!!w["audio/webm; codecs=opus"]}async pg(c){c=await this.md("runtime","opus-decode",{arrayBuffer:c},
null,[c]);return new Float32Array(c)}Be(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}kd(c){return!this.Be(c)}async xc(c,h){return"cordova"===this.B&&"module"===h&&(c.startsWith("file:")||"file:"===location.protocol&&this.kd(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),c=await this.ub(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async mf(c){const h=c.filename;switch(c.as){case "text":return await this.ue(h);case "buffer":return await this.ub(h);
default:throw Error("unsupported type");}}fd(c){const h=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(h,q=>{q.file(l,n)},n)})}async ue(c){c=await this.fd(c);return await A(c)}rc(){if(v.length&&!(8<=x)){x++;var c=v.shift();this.We(c.filename,c.Fg,c.Ag)}}ub(c){return new Promise((h,l)=>{v.push({filename:c,Fg:n=>{x--;this.rc();h(n)},Ag:n=>{x--;this.rc();l(n)}});this.rc()})}async We(c,h,l){try{const n=await this.fd(c),q=await B(n);
h(q)}catch(n){l(n)}}async Ve(){const c=[];for(const [h,l]of Object.entries(this.ia))c.push(this.Ue(h,l));await Promise.all(c)}async Ue(c,h){if("object"===typeof h)this.ia[c]=new Blob([h.str],{type:h.type}),this.Rb[c]=h.str;else{let l=await this.cf(h);l||(l=this.Ye(h));this.ia[c]=l}}async cf(c){try{return await (await fetch(c)).blob()}catch(h){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
h),null}}Ye(c){c=this.Mf(c);return this.Te(c.data,c.Cg)}Mf(c){var h=c.indexOf(",");if(0>h)throw new URIError("expected comma in data: uri");var l=c.substring(h+1);h=c.substring(5,h).split(";");c=h[0]||"";const n=h[2];l="base64"===h[1]||"base64"===n?atob(l):decodeURIComponent(l);return{Cg:c,data:l}}Te(c,h){var l=c.length;let n=l>>2,q=new Uint8Array(l),u=new Uint32Array(q.buffer,0,n),r,z;for(z=r=0;r<n;++r)u[r]=c.charCodeAt(z++)|c.charCodeAt(z++)<<8|c.charCodeAt(z++)<<16|c.charCodeAt(z++)<<24;for(l&=
3;l--;)q[z]=c.charCodeAt(z),++z;return new Blob([q],{type:h})}}}"use strict";
{const f=self.Ua;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(e){return new Promise((k,c)=>{const h=document.createElement("link");h.onload=()=>k(h);h.onerror=l=>c(l);h.rel=
"stylesheet";h.href=e;document.head.appendChild(h)})}function w(e){return new Promise((k,c)=>{const h=new Image;h.onload=()=>k(h);h.onerror=l=>c(l);h.src=e})}async function A(e){e=URL.createObjectURL(e);try{return await w(e)}finally{URL.revokeObjectURL(e)}}function B(e){return new Promise((k,c)=>{let h=new FileReader;h.onload=l=>k(l.target.result);h.onerror=l=>c(l);h.readAsText(e)})}async function v(e,k,c){if(!/firefox/i.test(navigator.userAgent))return await A(e);var h=await B(e);h=(new DOMParser).parseFromString(h,
"image/svg+xml");const l=h.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),q=l.getAttribute("height");if(!n.includes("%")&&!q.includes("%"))return await A(e)}l.setAttribute("width",k+"px");l.setAttribute("height",c+"px");h=(new XMLSerializer).serializeToString(h);e=new Blob([h],{type:"image/svg+xml"});return await A(e)}function x(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["canvas",
"body","html"]);function y(e){C.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function D(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await A(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const k=e.getBoundingClientRect();document.body.removeChild(e);return[k.width,k.height]}};self.C3_RasterSvgImageBlob=async function(e,
k,c,h,l){e=await v(e,k,c);const n=document.createElement("canvas");n.width=h;n.height=l;n.getContext("2d").drawImage(e,0,0,k,c);return n};let F=!1;document.addEventListener("pause",()=>F=!0);document.addEventListener("resume",()=>F=!1);function H(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}f.tb(class extends self.Qa{constructor(e){super(e,"runtime");this.Od=!0;this.Na=-1;this.Zc="any";this.Fd=this.Gd=!1;this.Tc=this.nb=this.ya=null;e.C("canvas","update-size",h=>
this.Kf(h));e.C("runtime","invoke-download",h=>this.xf(h));e.C("runtime","raster-svg-image",h=>this.Ef(h));e.C("runtime","get-svg-image-size",h=>this.vf(h));e.C("runtime","set-target-orientation",h=>this.If(h));e.C("runtime","register-sw",()=>this.Ff());e.C("runtime","post-to-debugger",h=>this.zd(h));e.C("runtime","go-to-script",h=>this.zd(h));e.C("runtime","before-start-ticking",()=>this.lf());e.C("runtime","debug-highlight",h=>this.pf(h));e.C("runtime","enable-device-orientation",()=>this.Se());
e.C("runtime","enable-device-motion",()=>this.Re());e.C("runtime","add-stylesheet",h=>this.kf(h));e.C("runtime","alert",h=>this.yc(h));e.C("runtime","hide-cordova-splash",()=>this.wf());const k=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",h=>{const l=h.target;k.has(l.tagName.toLowerCase())||x(l)||h.preventDefault()});const c=e.K;window.addEventListener("selectstart",y);window.addEventListener("gesturehold",y);c.addEventListener("selectstart",y);c.addEventListener("gesturehold",
y);window.addEventListener("touchstart",y,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",y,{passive:!1}),c.addEventListener("pointerdown",y)):c.addEventListener("touchstart",y);this.kb=0;window.addEventListener("mousedown",h=>{1===h.button&&h.preventDefault()});window.addEventListener("mousewheel",D,{passive:!1});window.addEventListener("wheel",D,{passive:!1});window.addEventListener("resize",()=>this.Lf());window.addEventListener("fullscreenchange",()=>this.Ac());
window.addEventListener("webkitfullscreenchange",()=>this.Ac());window.addEventListener("mozfullscreenchange",()=>this.Ac());window.addEventListener("fullscreenerror",h=>this.Bc(h));window.addEventListener("webkitfullscreenerror",h=>this.Bc(h));window.addEventListener("mozfullscreenerror",h=>this.Bc(h));e.jc()&&window.addEventListener("focusout",()=>{{const n=document.activeElement;if(n){var h=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));h="textarea"===
h?!0:"input"===h?l.has(n.type.toLowerCase()||"text"):x(n)}else h=!1}h||(document.scrollingElement.scrollTop=0)});this.Ia=new Set;this.Sb=new WeakSet;this.oa=!1}lf(){"cordova"===this.v.B?(document.addEventListener("pause",()=>this.Fc(!0)),document.addEventListener("resume",()=>this.Fc(!1))):document.addEventListener("visibilitychange",()=>this.Fc(document.hidden));return{isSuspended:!(!document.hidden&&!F)}}cd(){window.addEventListener("focus",()=>this.Gb("window-focus"));window.addEventListener("blur",
()=>{this.Gb("window-blur",{parentHasFocus:H()});this.kb=0});window.addEventListener("keydown",k=>this.yd("keydown",k));window.addEventListener("keyup",k=>this.yd("keyup",k));window.addEventListener("dblclick",k=>this.Cc("dblclick",k,d));window.addEventListener("wheel",k=>this.Bf(k));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",k=>{this.uc(k);this.Va("pointerdown",k)}),this.v.ra&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.nb=new self.He(()=>this.af(),
5),this.nb.Jd=!0,window.addEventListener("pointerrawupdate",k=>this.Cf(k))):window.addEventListener("pointermove",k=>this.Va("pointermove",k)),window.addEventListener("pointerup",k=>this.Va("pointerup",k)),window.addEventListener("pointercancel",k=>this.Va("pointercancel",k))):(window.addEventListener("mousedown",k=>{this.uc(k);this.Dc("pointerdown",k)}),window.addEventListener("mousemove",k=>this.Dc("pointermove",k)),window.addEventListener("mouseup",k=>this.Dc("pointerup",k)),window.addEventListener("touchstart",
k=>{this.uc(k);this.Eb("pointerdown",k)}),window.addEventListener("touchmove",k=>this.Eb("pointermove",k)),window.addEventListener("touchend",k=>this.Eb("pointerup",k)),window.addEventListener("touchcancel",k=>this.Eb("pointercancel",k)));const e=()=>this.Gc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}Gb(e,k){t(this,e,k||null,m)}wa(){return this.v.wa()}va(){return this.v.va()}Lf(){const e=
this.wa(),k=this.va();this.Gb("window-resize",{innerWidth:e,innerHeight:k,devicePixelRatio:window.devicePixelRatio});this.v.jc()&&(-1!==this.Na&&clearTimeout(this.Na),this.Ad(e,k,0))}Tf(e,k,c){-1!==this.Na&&clearTimeout(this.Na);this.Na=setTimeout(()=>this.Ad(e,k,c),48)}Ad(e,k,c){const h=this.wa(),l=this.va();this.Na=-1;h!=e||l!=k?this.Gb("window-resize",{innerWidth:h,innerHeight:l,devicePixelRatio:window.devicePixelRatio}):10>c&&this.Tf(h,l,c+1)}If(e){this.Zc=e.targetOrientation}lg(){const e=this.Zc;
if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(k=>console.warn("[Construct 3] Failed to lock orientation: ",k));else try{let k=!1;screen.lockOrientation?k=screen.lockOrientation(e):screen.webkitLockOrientation?k=screen.webkitLockOrientation(e):screen.mozLockOrientation?k=screen.mozLockOrientation(e):screen.msLockOrientation&&(k=screen.msLockOrientation(e));k||console.warn("[Construct 3] Failed to lock orientation")}catch(k){console.warn("[Construct 3] Failed to lock orientation: ",
k)}}Ac(){const e=f.ic();e&&"any"!==this.Zc&&this.lg();t(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.wa(),innerHeight:this.va()})}Bc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);t(this,"fullscreenerror",{isFullscreen:f.ic(),innerWidth:this.wa(),innerHeight:this.va()})}Fc(e){e?this.v.qc():this.v.Hc();t(this,"visibilitychange",{hidden:e})}yd(e,k){"Backspace"===k.key&&y(k);const c=b.get(k.code)||k.code;E(this,e,{code:c,key:k.key,which:k.which,repeat:k.repeat,altKey:k.altKey,
ctrlKey:k.ctrlKey,metaKey:k.metaKey,shiftKey:k.shiftKey,timeStamp:k.timeStamp},d)}Bf(e){t(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,timeStamp:e.timeStamp},d)}Cc(e,k,c){a(k)||E(this,e,{button:k.button,buttons:k.buttons,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,timeStamp:k.timeStamp},c)}Dc(e,k){if(!a(k)){var c=this.kb;"pointerdown"===e&&0!==c?e="pointermove":"pointerup"===
e&&0!==k.buttons&&(e="pointermove");E(this,e,{pointerId:1,pointerType:"mouse",button:k.button,buttons:k.buttons,lastButtons:c,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:k.timeStamp},d);this.kb=k.buttons;this.Cc(k.type,k,g)}}Va(e,k){if(this.nb&&"pointermove"!==e){var c=this.nb;c.cb||(K(c),c.Pb=Date.now())}c=0;"mouse"===k.pointerType&&(c=this.kb);E(this,e,{pointerId:k.pointerId,pointerType:k.pointerType,
button:k.button,buttons:k.buttons,lastButtons:c,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:k.width||0,height:k.height||0,pressure:k.pressure||0,tangentialPressure:k.tangentialPressure||0,tiltX:k.tiltX||0,tiltY:k.tiltY||0,twist:k.twist||0,timeStamp:k.timeStamp},d);"mouse"===k.pointerType&&(c="mousemove","pointerdown"===e?c="mousedown":"pointerup"===e&&(c="mouseup"),this.Cc(c,k,g),this.kb=k.buttons)}Cf(e){this.Tc=e;e=this.nb;if(-1===e.Oa){var k=Date.now(),c=k-e.Pb,h=e.rg;
c>=h&&e.Jd?(e.Pb=k,e.cb=!0,e.Kc(),e.cb=!1):e.Oa=self.setTimeout(e.ae,Math.max(h-c,4))}}af(){this.Va("pointermove",this.Tc);this.Tc=null}Eb(e,k){for(let c=0,h=k.changedTouches.length;c<h;++c){const l=k.changedTouches[c];E(this,e,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:k.timeStamp},d)}}uc(e){window!==window.top&&window.focus();this.wd(e.target)&&document.activeElement&&!this.wd(document.activeElement)&&document.activeElement.blur()}wd(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}Se(){this.Gd||(this.Gd=!0,window.addEventListener("deviceorientation",e=>this.rf(e)),window.addEventListener("deviceorientationabsolute",e=>this.sf(e)))}Re(){this.Fd||(this.Fd=!0,window.addEventListener("devicemotion",
e=>this.qf(e)))}rf(e){t(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},d)}sf(e){t(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}qf(e){let k=null;var c=e.acceleration;c&&(k={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var h=e.accelerationIncludingGravity;h&&(c={x:h.x||
0,y:h.y||0,z:h.z||0});h=null;const l=e.rotationRate;l&&(h={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});t(this,"devicemotion",{acceleration:k,accelerationIncludingGravity:c,rotationRate:h,interval:e.interval,timeStamp:e.timeStamp},d)}Kf(e){const k=this.v.K;k.style.width=e.styleWidth+"px";k.style.height=e.styleHeight+"px";k.style.marginLeft=e.marginLeft+"px";k.style.marginTop=e.marginTop+"px";this.Od&&(k.style.display="",this.Od=!1)}xf(e){const k=e.url;e=e.filename;const c=document.createElement("a"),
h=document.body;c.textContent=e;c.href=k;c.download=e;h.appendChild(c);c.click();h.removeChild(c)}async Ef(e){var k=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);k=k?await createImageBitmap(e,k):await createImageBitmap(e);return{imageBitmap:k,transferables:[k]}}async vf(e){return await self.C3_GetSvgImageSize(e.blob)}async kf(e){await p(e.url)}Gc(){var e=[...this.Ia];this.Ia.clear();if(!this.oa)for(const k of e)(e=k.play())&&
e.catch(()=>{this.Sb.has(k)||this.Ia.add(k)})}ua(e){if("function"!==typeof e.play)throw Error("missing play function");this.Sb.delete(e);let k;try{k=e.play()}catch(c){this.Ia.add(e);return}k&&k.catch(()=>{this.Sb.has(e)||this.Ia.add(e)})}Ca(e){this.Ia.delete(e);this.Sb.add(e)}Ab(e){this.oa=!!e}wf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}pf(e){if(e.show){this.ya||(this.ya=document.createElement("div"),this.ya.id="inspectOutline",document.body.appendChild(this.ya));
var k=this.ya;k.style.display="";k.style.left=e.left-1+"px";k.style.top=e.top-1+"px";k.style.width=e.width+2+"px";k.style.height=e.height+2+"px";k.textContent=e.name}else this.ya&&(this.ya.style.display="none")}Ff(){window.C3_RegisterSW&&window.C3_RegisterSW()}zd(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}hf(e,k){return this.v.md(this.Ya,"js-invoke-function",{name:e,params:k},void 0,void 0)}yc(e){alert(e.message)}})}"use strict";
async function M(f){if(f.qg)throw Error("already initialised");f.qg=!0;var a=f.Wb.tc("https://163820484-173520688372164925.preview.editmysite.com/uploads/b/139890129-219422933132087682/files/scripts/dispatchworker.js");f.Mc=await f.Wb.bc(a,f.F,{name:"DispatchWorker"});a=new MessageChannel;f.Qc=a.port1;f.Mc.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.Xc=await O(f)}function N(f){return[f.Qc,f.Xc]}
async function O(f){const a=f.Pd.length;var b=f.Wb.tc("https://163820484-173520688372164925.preview.editmysite.com/uploads/b/139890129-219422933132087682/files/scripts/jobworker.js");b=await f.Wb.bc(b,f.F,{name:"JobWorker"+a});const d=new MessageChannel,g=new MessageChannel;f.Mc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":g.port2},[d.port2,g.port2]);f.Pd.push(b);return g.port1}
self.De=class{constructor(f){this.Wb=f;this.F=f.F;this.F="preview"===f.B?this.F+"c3/workers/":this.F+f.Xb;this.tg=Math.min(navigator.hardwareConcurrency||2,16);this.Mc=null;this.Pd=[];this.Xc=this.Qc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Ua({Gg:!1,Hg:"workermain.js",Pa:["https://163820484-173520688372164925.preview.editmysite.com/uploads/b/139890129-219422933132087682/files/scripts/c3runtime.js"],sb:[],ce:"",de:"module",Dg:"scripts/",bd:[],be:"html5"}));"use strict";
async function P(f,a){a=a.type;let b=!0;0===a?b=await Q():1===a&&(b=await S());t(f,"permission-result",{type:a,result:b})}async function Q(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request orientation permission: ",f),!1}}
async function S(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request motion permission: ",f),!1}}self.Ua.tb(class extends self.Qa{constructor(f){super(f,"touch");G(this,"request-permission",a=>P(this,a))}});"use strict";
{const f=180/Math.PI;self.ea=class extends self.Qa{constructor(a){super(a,"audio");this.Lb=this.f=null;this.Nb=this.Pc=!1;this.qa=()=>this.mg();this.aa=[];this.D=[];this.ha=null;this.Qd="";this.Rd=-1;this.mb=new Map;this.Uc=1;this.oa=!1;this.$c=0;this.Zb=1;this.Nc=0;this.Td="HRTF";this.Kd="inverse";this.Ud=600;this.Sd=1E4;this.Wd=1;this.Md=this.Yc=!1;this.Zd=this.v.Ce();this.ba=new Map;this.Fa=new Set;this.Rc=!1;this.Vc="";this.za=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Af(b,d);this.Kb=null;
self.C3Audio_GetOutputStream=()=>this.uf();self.C3Audio_DOMInterface=this;I(this,[["create-audio-context",b=>this.Xe(b)],["play",b=>this.Nf(b)],["stop",b=>this.jg(b)],["stop-all",()=>this.kg()],["set-paused",b=>this.cg(b)],["set-volume",b=>this.hg(b)],["fade-volume",b=>this.bf(b)],["set-master-volume",b=>this.ag(b)],["set-muted",b=>this.bg(b)],["set-silent",b=>this.eg(b)],["set-looping",b=>this.$f(b)],["set-playback-rate",b=>this.dg(b)],["seek",b=>this.Uf(b)],["preload",b=>this.Of(b)],["unload",b=>
this.ng(b)],["unload-all",()=>this.og()],["set-suspended",b=>this.fg(b)],["add-effect",b=>this.rd(b)],["set-effect-param",b=>this.Xf(b)],["remove-effects",b=>this.Qf(b)],["tick",b=>this.Jf(b)],["load-state",b=>this.yf(b)]])}async Xe(a){a.isiOSCordova&&(this.Yc=!0);this.$c=a.timeScaleMode;this.Td=["equalpower","HRTF","soundfield"][a.panningModel];this.Kd=["linear","inverse","exponential"][a.distanceModel];this.Ud=a.refDistance;this.Sd=a.maxDistance;this.Wd=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.Zd||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.sd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.sd()};this.Lb=this.f.createGain();this.Lb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.cc();try{await Promise.all(a.preloadList.map(d=>this.Cb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}sd(){this.Nb||(this.Pc=!1,window.addEventListener("pointerup",this.qa,!0),window.addEventListener("touchend",this.qa,!0),window.addEventListener("click",this.qa,!0),window.addEventListener("keydown",this.qa,!0),this.Nb=!0)}Ze(){this.Nb&&(this.Pc=!0,window.removeEventListener("pointerup",this.qa,!0),window.removeEventListener("touchend",
this.qa,!0),window.removeEventListener("click",this.qa,!0),window.removeEventListener("keydown",this.qa,!0),this.Nb=!1)}mg(){if(!this.Pc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.Ze()}}W(){return this.f}cc(){return this.f.currentTime}sa(){return this.Lb}hd(a){return(a=this.ba.get(a.toLowerCase()))?a[0].P():this.sa()}ee(a,b){a=a.toLowerCase();let d=this.ba.get(a);
d||(d=[],this.ba.set(a,d));b.Zf(d.length);b.gg(a);d.push(b);this.Cd(a)}Cd(a){let b=this.sa();const d=this.ba.get(a);if(d&&d.length){b=d[0].P();for(let g=0,m=d.length;g<m;++g){const p=d[g];g+1===m?p.S(this.sa()):p.S(d[g+1].P())}}for(const g of this.ma(a))g.Ie(b);this.za&&this.Vc===a&&(this.za.disconnect(),this.za.connect(b))}wb(){return this.Uc}xb(){return this.oa}Yf(){this.Md=!0}we(a,b){return b?this.v.pg(a).then(d=>{const g=this.f.createBuffer(1,d.length,48E3);g.getChannelData(0).set(d);return g}):
new Promise((d,g)=>{this.f.decodeAudioData(a,d,g)})}ua(a){this.v.ua(a)}Ca(a){this.v.Ca(a)}nd(a){let b=0;for(let d=0,g=this.D.length;d<g;++d){const m=this.D[d];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Je(){let a=0;for(let b=0,d=this.aa.length;b<d;++b){const g=this.aa[b];this.aa[a]=g;g.ta()?g.c():++a}this.aa.length=a}*ma(a){if(a)for(const b of this.D)self.ea.xe(b.Z,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Cb(a,b,d,g,m){for(const p of this.aa)if(p.Sa()===b)return await T(p),
p;if(m)return null;g&&(this.Yc||this.Md)&&this.Je();m="audio/webm; codecs=opus"===d&&!this.Zd;g&&m&&this.Yf();a=!g||this.Yc||m?new self.se(this,a,b,d,g,m):new self.qe(this,a,b,d,g);this.aa.push(a);await T(a);return a}async sc(a,b,d,g,m){for(const p of this.D)if(p.Sa()===b&&(p.ac()||m))return p.Le(g),p;a=await this.Cb(a,b,d,m);g="html5"===a.Ic?new self.re(a.i,a,g):new self.te(a.i,a,g);this.D.push(g);return g}Pe(a){let b=this.mb.get(a);if(!b){let d=null;b={ad:0,promise:new Promise(g=>d=g),resolve:d};
this.mb.set(a,b)}b.ad++}Rf(a){const b=this.mb.get(a);if(!b)throw Error("expected pending tag");b.ad--;0===b.ad&&(b.resolve(),this.mb.delete(a))}pc(a){a||(a=this.Qd);return(a=this.mb.get(a))?a.promise:Promise.resolve()}Db(){if(0<this.Fa.size)J(this);else for(const a of this.D)if(a.jd()){J(this);break}}Da(){for(var a of this.Fa)a.Da();a=this.cc();for(var b of this.D)b.Da(a);b=this.D.filter(d=>d.jd()).map(d=>d.Ra());t(this,"state",{tickCount:this.Rd,audioInstances:b,analysers:[...this.Fa].map(d=>d.ze())});
0===b.length&&0===this.Fa.size&&this.Ob&&(this.v.Sf(this.$d),this.Ob=!1)}lc(a,b,d){t(this,"trigger",{type:a,tag:b,aiid:d})}async Nf(a){const b=a.originalUrl,d=a.url,g=a.type,m=a.isMusic,p=a.tag,w=a.isLooping,A=a.vol,B=a.pos,v=a.panning;let x=a.off;0<x&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+this.f.currentTime);this.Qd=p;this.Pe(p);try{this.ha=await this.sc(b,d,g,p,m),v?(this.ha.zb(!0),this.ha.Ke(v.x,
v.y,v.angle,v.innerAngle,v.outerAngle,v.outerGain),v.hasOwnProperty("uid")&&this.ha.Me(v.uid)):this.ha.zb(!1),this.ha.Play(w,A,B,x)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Rf(p)}J(this)}jg(a){a=a.tag;for(const b of this.ma(a))b.na()}kg(){for(const a of this.D)a.na()}cg(a){const b=a.tag;a=a.paused;for(const d of this.ma(b))a?d.Ta():d.yb();this.Db()}hg(a){const b=a.tag;a=a.vol;for(const d of this.ma(b))d.Bb(a)}async bf(a){const b=a.tag,d=a.vol,
g=a.duration;a=a.stopOnEnd;await this.pc(b);for(const m of this.ma(b))m.ye(d,g,a);this.Db()}ag(a){this.Uc=a.vol;for(const b of this.D)b.Ib()}bg(a){const b=a.tag;a=a.isMuted;for(const d of this.ma(b))d.od(a)}eg(a){this.oa=a.isSilent;this.v.Ab(this.oa);for(const b of this.D)b.Hb()}$f(a){const b=a.tag;a=a.isLooping;for(const d of this.ma(b))d.nc(a)}async dg(a){const b=a.tag;a=a.rate;await this.pc(b);for(const d of this.ma(b))d.qd(a)}async Uf(a){const b=a.tag;a=a.pos;await this.pc(b);for(const d of this.ma(b))d.mc(a)}async Of(a){const b=
a.originalUrl,d=a.url,g=a.type;a=a.isMusic;try{await this.sc(b,d,g,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async ng(a){if(a=await this.Cb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}og(){for(const a of this.aa)a.c();this.aa.length=0}fg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.oc(a);a&&this.f.suspend&&this.f.suspend()}Jf(a){this.Zb=a.timeScale;this.Nc=a.gameTime;this.Rd=a.tickCount;if(0!==
this.$c)for(var b of this.D)b.Ea();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const g of this.D)g.ga===a&&g.pd(d.x,d.y,d.angle)}}async rd(a){var b=a.type;const d=a.tag;var g=a.params;if("filter"===b)g=new self.ke(this,...g);else if("delay"===b)g=new self.ie(this,...g);else if("convolution"===b){b=null;try{b=await this.Cb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",
m);return}g=new self.he(this,b.$,...g);g.Vf(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.le(this,...g);else if("phaser"===b)g=new self.ne(this,...g);else if("gain"===b)g=new self.me(this,...g);else if("tremolo"===b)g=new self.pe(this,...g);else if("ringmod"===b)g=new self.oe(this,...g);else if("distortion"===b)g=new self.je(this,...g);else if("compressor"===b)g=new self.ge(this,...g);else if("analyser"===b)g=new self.fe(this,...g);else throw Error("invalid effect type");this.ee(d,
g);this.Bd()}Xf(a){const b=a.index,d=a.param,g=a.value,m=a.ramp,p=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,g,m,p),this.Bd())}Qf(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const d of b)d.c();this.ba.delete(a);this.Cd(a)}}Oe(a){this.Fa.add(a);this.Db()}Pf(a){this.Fa.delete(a)}Bd(){this.Rc||(this.Rc=!0,Promise.resolve().then(()=>this.$e()))}$e(){const a={};for(const [b,d]of this.ba)a[b]=d.map(g=>g.Ra());t(this,"fxstate",{fxstate:a});this.Rc=!1}async yf(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.D)d.ta()&&1===b||(d.ta()||2!==b)&&d.na();for(const g of this.ba.values())for(const m of g)m.c();this.ba.clear();this.Zb=a.timeScale;this.Nc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.oa=a.isSilent;this.v.Ab(this.oa);this.Uc=a.masterVolume;d=[];for(const g of Object.values(a.effects))d.push(Promise.all(g.map(m=>this.rd(m))));await Promise.all(d);await Promise.all(a.playing.map(g=>this.jf(g,b)));this.Db()}async jf(a,b){if(3!==
b){var d=a.bufferOriginalUrl,g=a.bufferUrl,m=a.bufferType,p=a.isMusic,w=a.tag,A=a.isLooping,B=a.volume,v=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.sc(d,g,m,w,p)}catch(x){console.error("[Construct 3] Audio: error loading audio state: ",x);return}b.Ge(a.pan);b.Play(A,B,v,0);a.isPlaying||b.Ta();b.wc(a)}}}Af(a,b){this.za&&this.za.disconnect();this.Vc=b.toLowerCase();this.za=this.f.createMediaStreamSource(a);this.za.connect(this.hd(this.Vc))}uf(){this.Kb||(this.Kb=this.f.createMediaStreamDestination(),
this.Lb.connect(this.Kb));return this.Kb.stream}static xe(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Ne(a){return a*f}static ve(a){return Math.pow(10,a/20)}static gd(a){return Math.max(Math.min(self.ea.ve(a),1),0)}static Fe(a){return Math.log(a)/Math.log(10)*20}static Ee(a){return self.ea.Fe(Math.max(Math.min(a,1),0))}static zg(a,b){return 1-Math.exp(-b*a)}};self.Ua.tb(self.ea)}"use strict";function T(f){f.Qb||(f.Qb=f.vc());return f.Qb}
self.dd=class{constructor(f,a,b,d,g){this.i=f;this.vg=a;this.Aa=b;this.R=d;this.sg=g;this.Ic="";this.Qb=null}c(){this.Qb=this.i=null}vc(){}W(){return this.i.W()}ec(){return this.vg}Sa(){return this.Aa}dc(){return this.R}ta(){return this.sg}fa(){}};"use strict";
self.qe=class extends self.dd{constructor(f,a,b,d,g){super(f,a,b,d,g);this.Ic="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.gb=this.hb=null;this.J.addEventListener("canplaythrough",()=>!0);this.lb=this.W().createGain();this.jb=null;this.J.addEventListener("canplay",()=>{this.hb&&(this.hb(),this.gb=this.hb=null);!this.jb&&this.J&&(this.jb=this.W().createMediaElementSource(this.J),this.jb.connect(this.lb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Aa}' error: `,m);this.gb&&(this.gb(m),this.gb=this.hb=null)})}c(){this.i.nd(this);this.lb.disconnect();this.lb=null;this.jb.disconnect();this.jb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}vc(){return new Promise((f,a)=>{this.hb=f;this.gb=a;this.J.src=this.Aa})}O(){return this.J}fa(){return this.J.duration}};"use strict";
async function U(f){if(f.xa)return f.xa;var a=f.i.v;if("cordova"===a.B&&a.kd(f.Aa)&&"file:"===location.protocol)f.xa=await a.ub(f.Aa);else{a=await fetch(f.Aa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.xa=await a.arrayBuffer()}}async function V(f){if(f.$)return f.$;f.$=await f.i.we(f.xa,f.ug);f.xa=null}
self.se=class extends self.dd{constructor(f,a,b,d,g,m){super(f,a,b,d,g);this.Ic="webaudio";this.$=this.xa=null;this.ug=!!m}c(){this.i.nd(this);this.$=this.xa=null;super.c()}async vc(){try{await U(this),await V(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.Aa}': `,f)}}fa(){return this.$?this.$.duration:0}};"use strict";
{let f=0;self.ed=class{constructor(a,b,d){this.i=a;this.L=b;this.Z=d;this.Jb=f++;this.M=this.W().createGain();this.M.connect(this.sa());this.A=null;this.eb=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.H=!0;this.V=this.la=this.G=!1;this.pb=1;this.Ga=!1;this.Y=1;a=this.i.$c;this.Sc=1===a&&!this.ta()||2===a;this.ab=this.ga=-1;this.Yd=!1}c(){this.L=this.i=null;this.A&&(this.A.disconnect(),this.A=null);this.M.disconnect();this.M=null}W(){return this.i.W()}sa(){return this.i.hd(this.Z)}wb(){return this.i.wb()}vb(){return this.Sc?
this.i.Nc:performance.now()/1E3}ec(){return this.L.ec()}Sa(){return this.L.Sa()}dc(){return this.L.dc()}ta(){return this.L.ta()}Le(a){this.Z=a}T(){}ac(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}jd(){return!this.H&&!this.T()}Ba(){}fa(){return this.L.fa()}Play(){}na(){}Ta(){}yb(){}Bb(a){this.pb=a;this.M.gain.cancelScheduledValues(0);this.ab=-1;this.M.gain.value=this.fc()}ye(a,b,d){if(!this.Ga){a*=this.wb();var g=this.M.gain;g.cancelScheduledValues(0);var m=this.i.cc();b=m+b;g.setValueAtTime(g.value,
m);g.linearRampToValueAtTime(a,b);this.pb=a;this.ab=b;this.Yd=d}}Ib(){this.Bb(this.pb)}Da(a){-1!==this.ab&&a>=this.ab&&(this.ab=-1,this.Yd&&this.na(),this.i.lc("fade-ended",this.Z,this.Jb))}fc(){const a=this.pb*this.wb();return isFinite(a)?a:0}od(a){a=!!a;this.Ga!==a&&(this.Ga=a,this.Hb())}xb(){return this.i.xb()}Hb(){}nc(){}qd(a){this.Y!==a&&(this.Y=a,this.Ea())}Ea(){}mc(){}oc(){}zb(a){a=!!a;this.eb!==a&&((this.eb=a)?(this.A||(this.A=this.W().createPanner(),this.A.panningModel=this.i.Td,this.A.distanceModel=
this.i.Kd,this.A.refDistance=this.i.Ud,this.A.maxDistance=this.i.Sd,this.A.rolloffFactor=this.i.Wd),this.M.disconnect(),this.M.connect(this.A),this.A.connect(this.sa())):(this.A.disconnect(),this.M.disconnect(),this.M.connect(this.sa())))}Ke(a,b,d,g,m,p){this.eb&&(this.pd(a,b,d),a=self.ea.Ne,this.A.coneInnerAngle=a(g),this.A.coneOuterAngle=a(m),this.A.coneOuterGain=p)}pd(a,b,d){this.eb&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(d),this.ja[1]=Math.sin(d),this.ja[2]=0,this.A.setPosition(...this.ka),
this.A.setOrientation(...this.ja))}Me(a){this.ga=a}hc(){}Ie(a){const b=this.A||this.M;b.disconnect();b.connect(a)}Ra(){return{aiid:this.Jb,tag:this.Z,duration:this.fa(),volume:this.pb,isPlaying:this.IsPlaying(),playbackTime:this.Ba(),playbackRate:this.Y,uid:this.ga,bufferOriginalUrl:this.ec(),bufferUrl:"",bufferType:this.dc(),isMusic:this.ta(),isLooping:this.V,isMuted:this.Ga,resumePosition:this.hc(),pan:this.Ae()}}wc(a){this.qd(a.playbackRate);this.od(a.isMuted)}Ae(){if(!this.A)return null;const a=
this.A;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Ge(a){if(a){this.zb(!0);a=this.A;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.zb(!1)}}}"use strict";
self.re=class extends self.ed{constructor(f,a,b){super(f,a,b);this.L.lb.connect(this.M);this.L.onended=()=>this.zc()}c(){this.na();this.L.lb.disconnect();super.c()}O(){return this.L.O()}zc(){this.H=!0;this.ga=-1;this.i.lc("ended",this.Z,this.Jb)}T(){return this.O().ended}ac(){return this.H?!0:this.T()}Ba(f){let a=this.O().currentTime;f&&(a*=this.Y);this.V||(a=Math.min(a,this.fa()));return a}Play(f,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==f&&(d.loop=f);this.Bb(a);d.muted&&
(d.muted=!1);if(d.currentTime!==b)try{d.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Sa()}' to position '${b}': `,g)}this.i.ua(d);this.G=this.H=!1;this.V=f;this.Y=1}na(){const f=this.O();f.paused||f.pause();this.i.Ca(f);this.H=!0;this.G=!1;this.ga=-1}Ta(){if(!(this.G||this.H||this.T())){var f=this.O();f.paused||f.pause();this.i.Ca(f);this.G=!0}}yb(){!this.G||this.H||this.T()||(this.i.ua(this.O()),this.G=!1)}Hb(){this.O().muted=this.Ga||this.xb()}nc(f){f=!!f;
this.V!==f&&(this.V=f,this.O().loop=f)}Ea(){let f=this.Y;this.Sc&&(f*=this.i.Zb);try{this.O().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}mc(f){if(!this.H&&!this.T())try{this.O().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}hc(){return this.Ba()}oc(f){f?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.ua(this.O()),this.la=!1)}};"use strict";
function W(f){f.j&&f.j.disconnect();f.j=null;f.Xa=null}
self.te=class extends self.ed{constructor(f,a,b){super(f,a,b);this.j=null;this.Tb=d=>this.zc(d);this.Oc=!0;this.Xa=null;this.N=this.Yb=0;this.Wc=1}c(){this.na();W(this);this.Tb=null;super.c()}zc(f){this.G||this.la||f.target!==this.Xa||(this.H=this.Oc=!0,this.ga=-1,W(this),this.i.lc("ended",this.Z,this.Jb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Oc}ac(){return!this.j||this.H?!0:this.T()}Ba(f){let a;a=this.G?this.N:this.vb()-this.Yb;f&&(a*=this.Y);this.V||(a=Math.min(a,this.fa()));return a}Play(f,
a,b,d){this.Wc=1;this.Bb(a);W(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.$;this.j.connect(this.M);this.Xa=this.j;this.j.onended=this.Tb;this.j.loop=f;this.j.start(d,b);this.G=this.H=this.Oc=!1;this.V=f;this.Y=1;this.Yb=this.vb()-b}na(){if(this.j)try{this.j.stop(0)}catch(f){}this.H=!0;this.G=!1;this.ga=-1}Ta(){this.G||this.H||this.T()||(this.N=this.Ba(!0),this.V&&(this.N%=this.fa()),this.G=!0,this.j.stop(0))}yb(){!this.G||this.H||this.T()||(W(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.L.$,this.j.connect(this.M),this.Xa=this.j,this.j.onended=this.Tb,this.j.loop=this.V,this.Ib(),this.Ea(),this.Yb=this.vb()-this.N/(this.Y||.001),this.j.start(0,this.N),this.G=!1)}fc(){return super.fc()*this.Wc}Hb(){this.Wc=this.Ga||this.xb()?0:1;this.Ib()}nc(f){f=!!f;this.V!==f&&(this.V=f,this.j&&(this.j.loop=f))}Ea(){let f=this.Y;this.Sc&&(f*=this.i.Zb);this.j&&(this.j.playbackRate.value=f)}mc(f){this.H||this.T()||(this.G?this.N=f:(this.Ta(),this.N=f,this.yb()))}hc(){return this.N}oc(f){f?
this.IsPlaying()?(this.la=!0,this.N=this.Ba(!0),this.V&&(this.N%=this.fa()),this.j.stop(0)):this.la=!1:this.la&&(W(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.Xa=this.j,this.j.onended=this.Tb,this.j.loop=this.V,this.Ib(),this.Ea(),this.Yb=this.vb()-this.N/(this.Y||.001),this.j.start(0,this.N),this.la=!1)}wc(f){super.wc(f);this.N=f.resumePosition}};"use strict";
{class f{constructor(a){this.i=a;this.f=a.W();this.Nd=-1;this.R=this.Z="";this.g=null}c(){this.f=null}Zf(a){this.Nd=a}gg(a){this.Z=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var m=this.f.currentTime;g+=m;switch(d){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,g)}}}Ra(){return{type:this.R,tag:this.Z,params:this.g}}}
self.ke=class extends f{constructor(a,b,d,g,m,p,w){super(a);this.R="filter";this.g=[b,d,g,m,p,w];this.l=this.o();this.b=this.o();this.b.gain.value=w;this.a=this.o();this.a.gain.value=1-w;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=d;this.u.detune.value=g;this.u.Q.value=m;this.u.gain.vlaue=p;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,d,g);break;case 2:this.g[2]=b;this.m(this.u.detune,b,d,g);break;case 3:this.g[3]=b;this.m(this.u.Q,b,d,g);break;case 4:this.g[4]=b,this.m(this.u.gain,b,d,g)}}};self.ie=class extends f{constructor(a,b,d,g){super(a);this.R="delay";this.g=[b,d,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.ib=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.$a=this.o();this.$a.gain.value=d;this.l.connect(this.ib);this.l.connect(this.a);this.ib.connect(this.b);this.ib.connect(this.U);this.U.connect(this.$a);this.$a.connect(this.ib)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.ib.disconnect();this.U.disconnect();this.$a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){const m=self.ea.gd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 4:this.g[1]=m(b);this.m(this.$a.gain,m(b),d,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,g)}}};self.he=class extends f{constructor(a,b,d,g){super(a);this.R="convolution";this.g=[d,g];this.Id=this.Hd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.Za=this.f.createConvolver();this.Za.normalize=d;this.Za.buffer=b;this.l.connect(this.Za);this.l.connect(this.a);this.Za.connect(this.b)}c(){this.l.disconnect();this.Za.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}Vf(a,b){this.Hd=a;this.Id=b}Ra(){const a=
super.Ra();a.bufferOriginalUrl=this.Hd;a.bufferUrl="";a.bufferType=this.Id;return a}};self.le=class extends f{constructor(a,b,d,g,m,p){super(a);this.R="flanger";this.g=[b,d,g,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.bb=this.o();this.bb.gain.value=m;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.I=this.o();this.I.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.bb);this.bb.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.bb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,d,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,d,g);break;case 8:this.g[3]=b/100,this.m(this.bb.gain,b/100,d,g)}}};self.ne=class extends f{constructor(a,b,d,g,m,p,w){super(a);this.R="phaser";this.g=[b,d,g,m,p,w];this.l=this.o();this.a=this.o();this.a.gain.value=1-w/2;this.b=this.o();this.b.gain.value=w/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
d;this.u.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=p;this.I=this.o();this.I.gain.value=m;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.I);this.I.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,d,g);break;case 2:this.g[1]=b;this.m(this.u.detune,b,d,g);break;case 3:this.g[2]=b;this.m(this.u.Q,b,d,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,d,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,d,g)}}};self.me=class extends f{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){const m=self.ea.gd;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),d,g)}}};self.pe=class extends f{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=d/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,g);this.m(this.I.gain,b/2,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.oe=class extends f{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.ob=this.o();this.ob.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.ob.gain);this.s.start(0);this.l.connect(this.ob);this.l.connect(this.a);this.ob.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.ob.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,g);
this.m(this.a.gain,1-b,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.je=class extends f{constructor(a,b,d,g,m,p){super(a);this.R="distortion";this.g=[b,d,g,m,p];this.l=this.o();this.Vb=this.o();this.Ub=this.o();this.Wf(g,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.$b=this.f.createWaveShaper();this.Lc=new Float32Array(65536);this.df(b,d);this.$b.curve=this.Lc;this.l.connect(this.Vb);this.l.connect(this.a);this.Vb.connect(this.$b);this.$b.connect(this.Ub);
this.Ub.connect(this.b)}c(){this.l.disconnect();this.Vb.disconnect();this.$b.disconnect();this.Ub.disconnect();this.b.disconnect();this.a.disconnect();super.c()}Wf(a,b){.01>a&&(a=.01);this.Vb.gain.value=a;this.Ub.gain.value=Math.pow(1/a,.6)*b}df(a,b){for(let d=0;32768>d;++d){let g=d/32768;g=this.ig(g,a,b);this.Lc[32768+d]=g;this.Lc[32768-d-1]=-g}}ig(a,b,d){d=1.05*d*b-b;const g=0>a?-a:a;return(g<b?g:b+d*self.ea.zg(g-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}};self.ge=class extends f{constructor(a,b,d,g,m,p){super(a);this.R="compressor";this.g=[b,d,g,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=g;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.fe=class extends f{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Ld=new Float32Array(this.h.frequencyBinCount);this.Xd=new Uint8Array(b);this.Vd=this.Ja=0;this.i.Oe(this)}c(){this.i.Pf(this);this.h.disconnect();super.c()}Da(){this.h.getFloatFrequencyData(this.Ld);this.h.getByteTimeDomainData(this.Xd);const a=this.h.fftSize;let b=this.Ja=0;for(var d=0;d<a;++d){let g=(this.Xd[d]-128)/128;0>g&&(g=-g);
this.Ja<g&&(this.Ja=g);b+=g*g}d=self.ea.Ee;this.Ja=d(this.Ja);this.Vd=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}ze(){return{tag:this.Z,index:this.Nd,peak:this.Ja,rms:this.Vd,binCount:this.h.frequencyBinCount,freqBins:this.Ld}}}}"use strict";function X(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>t(f,"sw-message",a.data))}
function Y(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(f):screen.webkitLockOrientation?a=screen.webkitLockOrientation(f):screen.mozLockOrientation?a=screen.mozLockOrientation(f):screen.msLockOrientation&&(a=screen.msLockOrientation(f));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.Ua.tb(class extends self.Qa{constructor(f){super(f,"browser");this.B="";I(this,[["get-initial-state",a=>{this.B=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>X(this)],
["alert",a=>this.yc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ec(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Y(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===b)window.forward();else if("home"===b)window.home();else if("reload"===b)location.reload();else if("url"===b){b=a.url;var d=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.Mg||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,d=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,d))}],
["request-fullscreen",a=>{{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?
document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{t(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{t(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{t(this,"hashchange",{location:location.toString()})});
document.addEventListener("backbutton",()=>{t(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",a=>{a.handled=!0;t(this,"backbutton")})}yc(f){alert(f.message)}Ec(f){f=f.isFocus;if("nwjs"===this.B){const a="nwjs"===this.B?nw.Window.get():null;f?a.focus():a.blur()}else f?window.focus():window.blur()}});
